/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */
module DIG_Add
#(
    parameter Bits = 1
)
(
    input [(Bits-1):0] a,
    input [(Bits-1):0] b,
    input c_i,
    output [(Bits - 1):0] s,
    output c_o
);
   wire [Bits:0] temp;

   assign temp = a + b + c_i;
   assign s = temp [(Bits-1):0];
   assign c_o = temp[Bits];
endmodule



module Mux_2x1
(
    input [0:0] sel,
    input in_0,
    input in_1,
    output reg out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule


module mod_adder_plus_K (
  input A0,
  input A1,
  input A2,
  input A3,
  input A4,
  input A5,
  input B0,
  input B1,
  input B2,
  input B3,
  input B4,
  input B5,
  input K0,
  input K1,
  input K2,
  input K3,
  input K4,
  input K5,
  input \0-3 ,
  input \0-1 ,
  input \0-2 ,
  input \0-8 ,
  input \0-5 ,
  input \0-6 ,
  input \0-7 ,
  input \0-4 ,
  output s6,
  output s5,
  output s4,
  output s3,
  output s2,
  output s1,
  output s0
);
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  wire s15;
  wire s16;
  wire s17;
  wire s18;
  wire s19;
  wire s20;
  wire s21;
  wire s22;
  wire s23;
  wire s24;
  wire s25;
  wire s26;
  wire s27;
  wire s28;
  wire s29;
  wire s30;
  wire s31;
  wire s32;
  wire s33;
  wire s34;
  wire s35;
  wire s36;
  wire s37;
  wire s38;
  wire s39;
  wire s40;
  wire s41;
  wire s42;
  wire s43;
  wire s44;
  wire s45;
  wire s46;
  wire s47;
  wire s48;
  wire s49;
  wire s50;
  wire s51;
  wire s52;
  wire s53;
  wire s54;
  wire s55;
  wire s56;
  wire s57;
  wire s58;
  wire s59;
  wire s60;
  wire s61;
  wire s62;
  wire s63;
  wire s64;
  wire s65;
  wire s66;
  wire s67;
  wire s68;
  wire s69;
  wire s70;
  wire s71;
  wire s72;
  wire s73;
  wire s74;
  wire s75;
  wire s76;
  wire s77;
  wire s78;
  wire s79;
  wire s80;
  wire s81;
  wire s82;
  wire s83;
  wire s84;
  wire s85;
  wire s86;
  wire s87;
  wire s88;
  wire s89;
  wire s90;
  wire s91;
  wire s92;
  wire s93;
  wire s94;
  wire s95;
  wire s96;
  wire s97;
  wire s98;
  wire s99;
  wire s100;
  wire s101;
  wire s102;
  wire s103;
  wire s104;
  assign s7 = (\0-7  & \0-6 );
  assign s8 = (\0-7  | \0-6 );
  assign s10 = (B5 & A5);
  assign s11 = (B5 | A5);
  assign s13 = (B4 & A4);
  assign s14 = (B4 | A4);
  assign s16 = (B3 & A3);
  assign s17 = (B3 | A3);
  assign s19 = (B2 & A2);
  assign s20 = (B2 | A2);
  assign s22 = (B1 & A1);
  assign s23 = (B1 | A1);
  assign s25 = (B0 & A0);
  assign s26 = (B0 | A0);
  assign s102 = ~ K1;
  assign s100 = ~ K2;
  assign s98 = ~ K3;
  assign s96 = ~ K4;
  assign s104 = ~ K0;
  assign s94 = ~ K5;
  assign s9 = (s8 & ~ s7);
  assign s12 = (s11 & ~ s10);
  assign s15 = (s14 & ~ s13);
  assign s18 = (s17 & ~ s16);
  assign s21 = (s20 & ~ s19);
  assign s24 = (s23 & ~ s22);
  assign s27 = (s26 & ~ s25);
  assign s67 = ((s11 & s13) | s10);
  assign s68 = ((s23 & s25) | s22);
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i0 (
    .a( s104 ),
    .b( \0-8  ),
    .c_i( \0-5  ),
    .s( s58 ),
    .c_o( s103 )
  );
  assign s47 = ~ s9;
  assign s49 = ~ s12;
  assign s51 = ~ s15;
  assign s53 = ~ s18;
  assign s55 = ~ s21;
  assign s57 = ~ s24;
  assign s59 = ~ s27;
  assign s72 = (((s20 & s17) & s68) | ((s17 & s19) | s16));
  assign s74 = ((s20 & s68) | s19);
  Mux_2x1 Mux_2x1_i1 (
    .sel( s58 ),
    .in_0( s25 ),
    .in_1( s26 ),
    .out( s43 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i2 (
    .a( s102 ),
    .b( \0-5  ),
    .c_i( s103 ),
    .s( s56 ),
    .c_o( s101 )
  );
  Mux_2x1 Mux_2x1_i3 (
    .sel( \0-4  ),
    .in_0( s9 ),
    .in_1( s47 ),
    .out( s29 )
  );
  Mux_2x1 Mux_2x1_i4 (
    .sel( s56 ),
    .in_0( s24 ),
    .in_1( s57 ),
    .out( s44 )
  );
  Mux_2x1 Mux_2x1_i5 (
    .sel( s58 ),
    .in_0( s27 ),
    .in_1( s59 ),
    .out( s45 )
  );
  Mux_2x1 Mux_2x1_i6 (
    .sel( s56 ),
    .in_0( s22 ),
    .in_1( s23 ),
    .out( s39 )
  );
  assign s76 = (((s14 & s11) & s72) | s67);
  assign s77 = ((s14 & s72) | s13);
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i7 (
    .a( s100 ),
    .b( \0-5  ),
    .c_i( s101 ),
    .s( s54 ),
    .c_o( s99 )
  );
  assign s46 = (\0-3  & s45);
  Mux_2x1 Mux_2x1_i8 (
    .sel( s54 ),
    .in_0( s21 ),
    .in_1( s55 ),
    .out( s40 )
  );
  Mux_2x1 Mux_2x1_i9 (
    .sel( s54 ),
    .in_0( s19 ),
    .in_1( s20 ),
    .out( s37 )
  );
  assign s65 = (s44 ^ s43);
  assign s66 = (s45 ^ \0-1 );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i10 (
    .a( s98 ),
    .b( \0-5  ),
    .c_i( s99 ),
    .s( s52 ),
    .c_o( s97 )
  );
  assign s41 = (s39 & s40);
  assign s42 = (s39 | s40);
  Mux_2x1 Mux_2x1_i11 (
    .sel( s52 ),
    .in_0( s18 ),
    .in_1( s53 ),
    .out( s38 )
  );
  Mux_2x1 Mux_2x1_i12 (
    .sel( s52 ),
    .in_0( s16 ),
    .in_1( s17 ),
    .out( s33 )
  );
  assign s64 = (s40 ^ s39);
  assign s71 = (((s43 | s44) & s46) | (s43 & s44));
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i13 (
    .a( s96 ),
    .b( \0-5  ),
    .c_i( s97 ),
    .s( s50 ),
    .c_o( s95 )
  );
  Mux_2x1 Mux_2x1_i14 (
    .sel( s50 ),
    .in_0( s15 ),
    .in_1( s51 ),
    .out( s34 )
  );
  Mux_2x1 Mux_2x1_i15 (
    .sel( s50 ),
    .in_0( s13 ),
    .in_1( s14 ),
    .out( s30 )
  );
  assign s63 = (s38 ^ s37);
  assign s73 = (((s42 & (s37 | s38)) & s71) | (((s37 | s38) & s41) | (s37 & s38)));
  assign s75 = ((s42 & s71) | s41);
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i16 (
    .a( s94 ),
    .b( \0-5  ),
    .c_i( s95 ),
    .s( s48 )
  );
  assign s35 = (s33 & s34);
  assign s36 = (s33 | s34);
  Mux_2x1 Mux_2x1_i17 (
    .sel( s48 ),
    .in_0( s12 ),
    .in_1( s49 ),
    .out( s31 )
  );
  Mux_2x1 Mux_2x1_i18 (
    .sel( s48 ),
    .in_0( s10 ),
    .in_1( s11 ),
    .out( s28 )
  );
  assign s62 = (s34 ^ s33);
  assign s32 = (s30 | s31);
  assign s60 = (s29 ^ s28);
  assign s61 = (s31 ^ s30);
  assign s79 = ((s36 & s73) | s35);
  assign s69 = ((s32 & s35) | (s30 & s31));
  assign s70 = (s36 & s32);
  assign s78 = ((s70 & s73) | s69);
  assign s80 = ~ ((((s70 & (s28 | s29)) & s73) | (((s28 | s29) & s69) | (s28 & s29))) | (((s32 & s8) & s72) | ((s8 & s67) | s7)));
  Mux_2x1 Mux_2x1_i19 (
    .sel( s80 ),
    .in_0( s60 ),
    .in_1( s9 ),
    .out( s81 )
  );
  Mux_2x1 Mux_2x1_i20 (
    .sel( s80 ),
    .in_0( s61 ),
    .in_1( s12 ),
    .out( s82 )
  );
  Mux_2x1 Mux_2x1_i21 (
    .sel( s80 ),
    .in_0( s62 ),
    .in_1( s15 ),
    .out( s83 )
  );
  Mux_2x1 Mux_2x1_i22 (
    .sel( s80 ),
    .in_0( s63 ),
    .in_1( s18 ),
    .out( s84 )
  );
  Mux_2x1 Mux_2x1_i23 (
    .sel( s80 ),
    .in_0( s64 ),
    .in_1( s21 ),
    .out( s85 )
  );
  Mux_2x1 Mux_2x1_i24 (
    .sel( s80 ),
    .in_0( s65 ),
    .in_1( s24 ),
    .out( s86 )
  );
  Mux_2x1 Mux_2x1_i25 (
    .sel( s80 ),
    .in_0( s78 ),
    .in_1( s76 ),
    .out( s87 )
  );
  Mux_2x1 Mux_2x1_i26 (
    .sel( s80 ),
    .in_0( s79 ),
    .in_1( s77 ),
    .out( s88 )
  );
  Mux_2x1 Mux_2x1_i27 (
    .sel( s80 ),
    .in_0( s73 ),
    .in_1( s72 ),
    .out( s89 )
  );
  Mux_2x1 Mux_2x1_i28 (
    .sel( s80 ),
    .in_0( s75 ),
    .in_1( s74 ),
    .out( s90 )
  );
  Mux_2x1 Mux_2x1_i29 (
    .sel( s80 ),
    .in_0( s71 ),
    .in_1( s68 ),
    .out( s91 )
  );
  Mux_2x1 Mux_2x1_i30 (
    .sel( s80 ),
    .in_0( s46 ),
    .in_1( s25 ),
    .out( s92 )
  );
  Mux_2x1 Mux_2x1_i31 (
    .sel( s80 ),
    .in_0( s66 ),
    .in_1( s27 ),
    .out( s93 )
  );
  assign s6 = (s81 ^ s87);
  assign s5 = (s82 ^ s88);
  assign s4 = (s83 ^ s89);
  assign s3 = (s84 ^ s90);
  assign s2 = (s85 ^ s91);
  assign s1 = (s86 ^ s92);
  assign s0 = (\0-2  ^ s93);
endmodule
